export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_FOOD = 'ADD_FOOD';
export const GET_MENU_LIST = 'GET_MENU_LIST';
export const FETCHING_MENU_SUCCESS = 'FETCHING_MENU_SUCCESS';
export const FETCHING_MENU_FAIL  = 'FETCHING_MENU_FAIL';
export const DELETE_CATEGORY  = 'DELETE_CATEGORY';
